name: Docker-img-build

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI-build"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag html_solomka_dev:$(date +%s)