name: CD DEPLOY TO SERVER
on:
  workflow_run:
    workflows: ["CI TESTS"]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
                  ls -al



#        run: rsync -avz . sergio@85.209.75.243 -p 2222 :/home/sergio/DOCKER_FILES/

