name: CD DEPLOY TO SERVER
on:
  workflow_run:
    workflows: ["CI TESTS"]
    types:
      - completed
jobs:
  build:
    name: Send script to Server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/sergio/DOCKER_FILES/html-solomka.dev
            cd ..
            rm -rf html-solomka.dev
            git clone https://github.com/Sergiy-Solomka/solomka.dev-layout.git /home/sergio/DOCKER_FILES/html-solomka.dev
            cd /home/sergio/DOCKER_FILES/html-solomka.dev
            echo Sergio | sudo -S docker build -t html_solomka_dev .
            echo Sergio | sudo -S docker compose up -d