name: CD DEPLOY TO SERVER
on:
  workflow_run:
    workflows: ["CI TESTS"]
    types:
      - completed
jobs:
  build:
    name: Send script to Server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ls -al
            cd /home/sergio/DOCKER_FILES/test
            cd ..
            rm -rf test
            git clone https://github.com/Sergiy-Solomka/solomka.dev-layout.git /home/sergio/DOCKER_FILES/test
            sudo -S docker build -t html_solomka_dev .
            sudo -S docker run -it -d -p 5006:80 html_solomka_dev