name: CI TESTS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  CI-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install server modules
        run: cd server && npm install
      - name: Install frontend modules
        run: cd frontend && npm install
